### ISSUE TITLE
Cannot use `querystring as qs`

### ISSUE THREAD

**Issue by bibz** [ababic/django-querystring-tag#12]
Hi @ababic, thanks for this neat library, I find it very helpful.

As advertised in the README, I wanted to make use of the `as` special argument to store the querystring in a template variable.
The catch is that I wanted _the whole querystring_, not a subpart, so I tried `{% querystring as qs %}` and it hit a rough corner.

Unless I missed something, this should be supported by the tag.

**Comment by ababic** [comment]
Nice find @bibz, and glad you are finding the package useful :)

Using `as` without any modifications is definitely something I'd like to support, as it makes no sense to have that limitation. 

The PR looks spot on, thank you :)
